import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from './components/sidebar'


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

    <div className='flex'>
        <div className='bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[08rem] lg:max-w'>
            <Sidebar/>
          </div>
          <div className='flex-1 bg-[#343541]'>
        {children}
        </div>
    </div>
      </body>
    </html>
  );
}
